package:
  name: pyfib
  version: 0.2

requirements:
  build:
    - setuptools
    - python
    - pandas <=0.16.1
    - fwrapper 0.2
  run:
    - setuptools
    - python
    - pandas
    - fwrapper 0.2

about:
  home: http://www.github.com/OpenSourcePolicyCenter
